"""empty message

Revision ID: 42a50712d48a
Revises: 
Create Date: 2020-01-23 16:37:32.384018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a50712d48a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'specialty', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialty', type_='foreignkey')
    op.drop_column('specialty', 'exam_id')
    # ### end Alembic commands ###
